name: FFCSA
version: "0.9.4"
date: 2023-04-20
description: |
    FFCSA - Finite Field Constructions, Search and Algorithms

authors:
    - name: Nusa Zidaric
      url: http://comsec.uwaterloo.ca/

maintainers:
    - name: Nusa Zidaric
      url: http://comsec.uwaterloo.ca/

GAP: "4.8"

needed-pkgs:
    - name: "GAPDoc"
      version: "1.6"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "FSR"
      version: "1.0.0"
      url: "https://nzidaric.github.io/FSR"

www: https://nzidaric.github.io/ffcsa
readme: README.md
packageinfo: https://nzidaric.github.io/ffcsa/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/nzidaric/ffcsa/releases/download/v0.9.4/FFCSA-0.9.4.tar.gz

abstract: |
    This package was designed for implementations of (cryptographic) hardware based on finite field arithmetic.

status: dev
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    package FFCSA, finite fields, constructions, representations, search, algorithms.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Zid23</span>]   <b class='BibAuthor'>Zidaric, N.</b>,
     <i class='BibTitle'>FFCSA, FFCSA - Finite Field Constructions, Search and Algorithms,
             Version 0.9.4</i>
     (<span class='BibYear'>2023</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://nzidaric.github.io/ffcsa">https://nzidaric.github.io/ffcsa</a></span>.
    </p>
    

bibtex: |
    @misc{ FFCSA0.9.4,
      author =           {Zidaric, N.},
      title =            {{FFCSA},  FFCSA  -  Finite Field Constructions, Search
                          and Algorithms, {V}ersion 0.9.4},
      month =            {Apr},
      year =             {2023},
      note =             {GAP package},
      howpublished =     {\href               {https://nzidaric.github.io/ffcsa}
                          {\texttt{https://nzidaric.github.io/}\discretionary
                          {}{}{}\texttt{ffcsa}}},
      keywords =         {package    FFCSA;    finite   fields;   constructions;
                          representations; search; algorithms},
      printedkey =       {Zid23}
    }

